#更改springboot端口号(默认是8080)
server:
  port: 8090


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.126.97.44:3306/Alianyi_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: alianyi
    password: Alianyi2018.cn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      indent_output: true

## Dubbo 服务提供者配置
#spring:
#  dubbo:
#    application:
#      name: provider
#    registry:
#      address:
#        zookeeper: //118.126.97.44:2181
#    protocol:
#      name: dubbo
#      port: 2888
#    scan: cn.alianyi.dailylife.commondao.dubbo
